# **Task 3**

***Apply Function***

**1. use the apply() function to categorize individuals as "High Income" or "Low Income" based on whether their AnnualIncome is above or below the median income?**

**2. How can you apply a function to calculate the difference between InterestRate and BaseInterestRate for each row and add it as a new column called RateDifference? ​​**

In [ ]:
import pandas as pd

In [ ]:
loan_df = pd.read_csv("/content/Loan.csv")

**use the apply() function to categorize individuals as "High Income" or "Low Income" based on whether their AnnualIncome is above or below the median income?**

In [ ]:

median_income = loan_df['AnnualIncome'].median()


def categorize_income(income):
    if income > median_income:
        return "High Income"
    else:
        return "Low Income"

loan_df['IncomeCategory'] = loan_df['AnnualIncome'].apply(categorize_income)


loan_df[['AnnualIncome', 'IncomeCategory']].head()

   AnnualIncome IncomeCategory
0         39948     Low Income
1         39709     Low Income
2         40724     Low Income
3         69084    High Income
4        103264    High Income

In [ ]:
#SAME WITH LAMBDA FUNCTION


loan_df['IncomeCategory'] = loan_df['AnnualIncome'].apply(lambda x: 'High Income' if x > median_income else 'Low Income')

loan_df[['AnnualIncome', 'IncomeCategory']].head()

   AnnualIncome IncomeCategory
0         39948     Low Income
1         39709     Low Income
2         40724     Low Income
3         69084    High Income
4        103264    High Income

**How can you apply a function to calculate the difference between InterestRate and BaseInterestRate for each row and add it as a new column called RateDifference? ​​**

In [ ]:
def calculate_rate_difference(row):
    return row['InterestRate'] - row['BaseInterestRate']

loan_df['RateDifference'] = loan_df.apply(calculate_rate_difference, axis=1)
loan_df[['InterestRate', 'BaseInterestRate', 'RateDifference']].head()

   InterestRate  BaseInterestRate  RateDifference
0      0.227590          0.199652        0.027938
1      0.201077          0.207045       -0.005968
2      0.212548          0.217627       -0.005079
3      0.300911          0.300398        0.000513
4      0.175990          0.197184       -0.021194

In [ ]:
#SAME WITH LAMBDA FUNCTION
loan_df['RateDifference'] = loan_df.apply(lambda row: row['InterestRate'] - row['BaseInterestRate'], axis=1)

loan_df[['InterestRate', 'BaseInterestRate', 'RateDifference']].head()

   InterestRate  BaseInterestRate  RateDifference
0      0.227590          0.199652        0.027938
1      0.201077          0.207045       -0.005968
2      0.212548          0.217627       -0.005079
3      0.300911          0.300398        0.000513
4      0.175990          0.197184       -0.021194